name: docs-post
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - pip
  - sphinx
  - sphinx-copybutton
  - sphinx-design
  - myst-nb
  - myst-parser
  - obspy
  - seispy
  - pip:
    - sphinx-gallery
    - sphinx-cjkspace
    - sphinxcontrib-bibtex
    - sphinx-icon
    - furo
